apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: peppamon-versa-collector-prom
    name: peppamon-versa-collector-prom
  name: peppamon-versa-collector-prom
  namespace: monitoring
spec:
  ports:
    - port: 2112
      protocol: TCP
      targetPort: 2112
      name: prom      
  selector:
    app: peppamon-versa-collector
  type: ClusterIP
status:
  loadBalancer: {}
