apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    app: peppamon-versa-collector
    release: peppamon-operator
  name: peppamon-versa-collector
  namespace: monitoring
spec:
  endpoints:
    - interval: 1m
      scrapeTimeout: 5m
      path: /metrics
      port: prom
      relabelings:
        - action: labeldrop
          regex: ^pod$
        - regex: .*
          replacement: peppamon-collector-versa
          sourceLabels:
          - __address__
          targetLabel: instance
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      name: peppamon-versa-collector-prom
