apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    app: peppamon-versa-collector
    release: peppamon-operator
  name: peppamon-versa-collector
  namespace: monitoring
spec:
  endpoints:
  - port: prom
    path: /metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      name: peppamon-versa-collector-prom
